/** @format */

const oneRooms = [
  {
    id: 0,
    title: '신림동 신축 원룸',
    image: 'https://codingapple1.github.io/vue/room0.jpg',
    content: '18년 신축공사한 남향 원룸 ☀️, 공기청정기 제공',
    price: 340000,
    monRent: 60,
    deposit: 500,
    reports: 0,
  },
  {
    id: 1,
    title: '공용 셰어하우스',
    image: 'https://codingapple1.github.io/vue/room1.jpg',
    content: '침실만 따로 있는 공용 셰어하우스입니다. 최대 2인 가능',
    price: 450000,
    monRent: 20,
    deposit: 200,
    reports: 0,
  },
  {
    id: 2,
    title: '금산오거리 아파트',
    image: 'https://codingapple1.github.io/vue/room2.jpg',
    content: '금산오거리 역세권 아파트입니다. 애완동물 불가능 ?',
    price: 780000,
    monRent: 60,
    deposit: 2000,
    reports: 0,
  },
  {
    id: 3,
    title: '무암동 인근 2인용 원룸',
    image: 'https://codingapple1.github.io/vue/room3.jpg',
    content: '무암동인근 2인용 원룸입니다. 전세 전환가능',
    price: 550000,
    monRent: 60,
    deposit: 1000,
    reports: 0,
  },
  {
    id: 4,
    title: '탄천동 아파트',
    image: 'https://codingapple1.github.io/vue/room4.jpg',
    content: '탄천동 아파트 월세, 남향, 역 5분거리, 허위매물아님',
    price: 680000,
    monRent: 49,
    deposit: 1000,
    reports: 0,
  },
  {
    id: 5,
    title: '반지하 원룸',
    image: 'https://codingapple1.github.io/vue/room5.jpg',
    content: '반지하 원룸입니다. 비올 때 물가끔 새는거 빼면 좋아요',
    price: 370000,
    monRent: 20,
    deposit: 300,
    reports: 0,
  },
];

export default oneRooms;
